### ISSUE TITLE
Login CEI-B3 com reCAPTCHA

### ISSUE THREAD

**Issue by renanleonellocastro** [guilhermecgs/ir#10]
Opa, beleza guilherme e comunidade, tudo bem?

Já conversamos há um tempo sobre o sistema de cálculo de imposto que estamos fazendo parecido. 

To criando essa issue para perguntar se vocês já se depararam com uma característica nova agora do login no cei-b3, o sistema está requerindo uma solução de recaptcha. Vocês já chegaram a implementar algo para isso? Eu ainda estou pensando em como fazer isso, queria trocar umas ideias para ver qual seria a melhor solução para isso.... Esbarrei com esse problema hoje ao testar o sistema (https://github.com/renanleonellocastro/darf_generator). Criei uma issue para isso tbm lá.

**Comment by guilhermecgs** [comment]
Bem problematico isso...

o reCAPTCHA foi feito exatamente para evitar o que estamos tentando fazer, entao é bem provavel que seja bem dificil contorna-lo na forca bruta. Alguns sites e links fornecem algumas tentativas, mas no fim das contas qualquer solucao seria prontamente respondida por uma atualizacao do google no reCAPTCHA. Daria para tentar algo pela posicao do checkbox na pagina, mas o reCAPTCHA é inteligente... Se vc rodar em uma aba anonima ele ja pede outras coisas mais complexas.

O unico jeito que vejo é uma execucao manual do script no selenium com chrome headless=false. Ou seja, eu coloco o codigo para rodar na minha maquina e quando entrar no reCAPTCHA eu manualmente digito e depois deixo o script continuar a execucao automatica. Iria funcionar imagino eu, mas teria que ter uma minima intervencao manual.

Agora, que foda essa b3 hein... so faz merda. Em vez de liberar uma API eles so pioram...  Tem varios sites que dependem disso

**Comment by renanleonellocastro** [comment]
Eu pensei nisso também, em colocar a intervenção manual. Acho que é a única forma. Eu cheguei a fazer isso já no sistema da receita para gerar o boleto, mas no caso do cei vai ser mais complexo devido a ser o reCAPTCHA do google e ele ser variável no que ele pede de resposta.... Estou um pouco preocupado de isso agora ferrar com o sistema...

**Comment by renanleonellocastro** [comment]
Achei esse sistema aqui também que parece que já adicionou um tratamento para o recaptcha. Não sei se funciona pois não testei ainda, mas vale o teste acho. https://github.com/gicornachini/bolsa

**Comment by guilhermecgs** [comment]
ok..

sobrando um tempo eu vou usar o codigo do link para testar...

**Comment by renanleonellocastro** [comment]
:+1:

**Comment by dalmago** [comment]
Olá pessoal. Entrando na discussão aí, vocês já chegaram a testar [essa API](https://developers.b3.com.br/index.php?option=com_apiportal&view=documentation&id=b8b024fd-0514-4793-9937-9983153087c7&app=B3%20Investidor&api=Posi%C3%A7%C3%A3o)?

**Comment by renanleonellocastro** [comment]
Opa, beleza dalmago? Obrigado por compartilhar isso, não conhecia.
Aparentemente será um serviço pago isso ai, confere?
![image](https://user-images.githubusercontent.com/10985679/100489944-5b7def00-30f6-11eb-8135-21940fced62d.png)

**Comment by guilhermecgs** [comment]
@dalmago , boa

tinha visto algo no passado, mas ainda estava muito cru.  Agora me pareceu que está caminhando, apesar de ainda estar em beta. Nao me importaria de pagar alguns centavos para o acesso.

Vou pedir para testar

**Comment by guilhermecgs** [comment]
mandei email para o pessoal da B3, mas deve demorar a responder.

As apis que nao possuem dados privados estao funcionando, mas o acesso a conta de um usuário (dados privados) é obviamente mais complexo. Vc (desenvolvedor/empresa) tem que se cadastrar no site da B3 em um pacote de acesso. Ainda nao sei exatamente como fazer, por isso o email.

Uma vez tendo esse pacote de acesso, vc utiliza o client_id que foi fornecido para abrir uma janela da B3 onde o usuário final autoriza vc (desenvolvedor/client_id) a acessar os dados. Essa autorizacao é feita por login/senha (do usuário final).

Com isso o desenvolvedor poderá solicitar tokens de acesso e seguir ....

**Comment by franciswagner** [comment]
Salve pessoal,
Pra fazer voltar a funcionar o login com o CEI basta utilizar essa url: https://ceiapp.b3.com.br/CEI_Responsivo/login.aspx

A B3 criou um servidor espelho sem o captcha justamente para bots utilizarem. A url antiga (com captcha) estava sendo afetada pela quantidade de acessos.

**Comment by guilhermecgs** [comment]
so de curiosidade, como tu descobriu isso?

**Comment by franciswagner** [comment]
@guilhermecgs Eu trabalho no [App Renda Fixa](https://www.apprendafixa.com.br) e tenho contatos com o pessoal da B3.

**Comment by renanleonellocastro** [comment]
Que bacana @franciswagner! Obrigado por compartilhar conosco. Isso vai salvar o projeto hehe

**Comment by mdmota** [comment]
> Salve @guilhermecgs,
> Pra fazer voltar a funcionar o login com o CEI basta utilizar essa url: https://ceiapp.b3.com.br/CEI_Responsivo/login.aspx
> 
> A B3 criou um servidor espelho sem o captcha justamente para bots utilizarem. A url antiga (com captcha) estava sendo afetada pela quantidade de acessos.

pq eles nao soltam uma api logo?

**Comment by mathmach** [comment]
> > Salve @guilhermecgs,
> > Pra fazer voltar a funcionar o login com o CEI basta utilizar essa url: https://ceiapp.b3.com.br/CEI_Responsivo/login.aspx
> > A B3 criou um servidor espelho sem o captcha justamente para bots utilizarem. A url antiga (com captcha) estava sendo afetada pela quantidade de acessos.
> 
> pq eles nao soltam uma api logo?

eles estão fazendo a API, mas ainda esta em teste https://developers.b3.com.br/

**Comment by julianogv** [comment]
> > > Salve @guilhermecgs,
> > > Pra fazer voltar a funcionar o login com o CEI basta utilizar essa url: https://ceiapp.b3.com.br/CEI_Responsivo/login.aspx
> > > A B3 criou um servidor espelho sem o captcha justamente para bots utilizarem. A url antiga (com captcha) estava sendo afetada pela quantidade de acessos.
> > 
> > 
> > pq eles nao soltam uma api logo?
> 
> eles estão fazendo a API, mas ainda esta em teste https://developers.b3.com.br/

Sabe se essa API estará disponivel para pessoa fisica acessar seu proprio dado ou somente para parceiros da B3 (igual o open banking)?

**Comment by guilhermecgs** [comment]
@julianogv , @mathmach , @franciswagner 

por acaso ja estao com acesso a essa API da B3?

**Comment by mdmota** [comment]
> @julianogv , @mathmach , @franciswagner
> 
> por acaso ja estao com acesso a essa API da B3?

Acesso sim, mas com varias duvidas. o suporte deles é bem confuso. 
Mas nao esta completa ainda.
Voce ja integrou?

**Comment by julianogv** [comment]
> > @julianogv , @mathmach , @franciswagner
> > por acaso ja estao com acesso a essa API da B3?
> 
> Acesso sim, mas com varias duvidas. o suporte deles é bem confuso. Mas nao esta completa ainda. Voce ja integrou?

@mdmota não, pelo que consegui entender do que conversei com o suporte deles o acesso será somente para empresas que contratarem o serviço ($).

Você fez desta forma?

**Comment by mdmota** [comment]
Sim, somente para empresa. e só respondem se as duvidas forem enviadas pelo dominio da empresa.
Sobre api ok, o retorno deles de callback de login é que nao esta pronto e nao sei como vai ser.

**Comment by guilhermecgs** [comment]
ai ferrou hein!
que falta de consideracao com dev pessoa fisica.

vamos ver quanto tempo ainda deixam o CEI funcionando

**Comment by mdmota** [comment]
Eu tinha entendido que dezembro ja sairia a versao release. Mas nada né?

**Comment by julianogv** [comment]
@mdmota sabe me dizer se tem algum filtro para que somente empresas consideradas fintech/bancos/corretoras possam contratar esta API ou qualquer empresa de qualquer ramo/tamanho pode contratar?

**Comment by mdmota** [comment]
Não sei te dizer. Pelo menos na apresentação não falaram de algum impedimento.
