### ISSUE TITLE
Problemas com as variáveis de ambiente

### ISSUE THREAD

**Issue by Rafaeltdcs** [guilhermecgs/ir#15]
Boa noite Guilherme,

Estou com uma dúvida nas várias de ambiente. Eu crio o caminho no windows porém não quando rodo o comando não encontra, tenho que fazer mais algum setup?

**Comment by Rafaeltdcs** [comment]
Já tinha outras issues sobre isso.

**Comment by guilhermecgs** [comment]
Resolvido?
