### ISSUE TITLE
problemas a utilizar. 

### ISSUE THREAD

**Issue by qwertytestenow** [guilhermecgs/ir#3]
Olá, Boa tarde, tudo bem? amigo guilherme, aqui é o Junior, eu não sou programador python, mais me interessei pelo seu tema aqui na aplicação , então quero saber se vc pode me dar uma dica mais pratica de como o executar e realizar as devidas configurações, tudo bem ? 
Desde já obrigado.

**Comment by guilhermecgs** [comment]
@qwertytestenow cara, se vc nao sabe python ficaria dificil explicar. Tem que saber minimamente executar um script.

**Comment by qwertytestenow** [comment]
Opa. Pois bem parceiro acho que sei executar sim um script, só queria o direcionamento mesmo nas configurações das variáve

**Comment by qwertytestenow** [comment]
🤙

**Comment by guilhermecgs** [comment]
@qwertytestenow 
As variaveis sao variaveis de ambientes que devem ser configuradas antes da execucao. De uma olhada nesse video

https://www.youtube.com/watch?v=hVyDkKh7IMg

As variaveis que devem ser configuradas sao as desse exemplo https://github.com/guilhermecgs/ir#exemplo-de-varaiveis-de-ambiente

Todas sao auto explicativas, exceto a API do dropbox, que deve ser gerada nesse link:
https://blogs.dropbox.com/developers/2014/05/generate-an-access-token-for-your-own-account/

**Comment by qwertytestenow** [comment]
opa, na hora amigo. obrigado. é que assim a execução troca de variáveis isso é tranquilo e configuração da API, só não rola aqui a execução. uma dúvida. ele utiliza o docker se for no mac?
