### ISSUE TITLE
Reconhecimento - Projetos parecidos

### ISSUE THREAD

**Issue by renanleonellocastro** [guilhermecgs/ir#7]
Opa guilherme, beleza?

Primeiramente peço desculpas por ter entrado em contato via "Issues". Talvez devido a minha falta de conhecimento, não encontrei outra forma de prestar reconhecimento ao seu trabalho e também mostrar meu interesse no seu projeto.

Parabéns pelo seu projeto. Eu, infelizmente, estou trabalhando em um projeto muito parecido com o seu, diria até que praticamente idêntico ([Gerador de DARF](https://github.com/renanleonellocastro/darf_generator)). Na época cheguei a procurar por bastante tempo sobre projetos parecidos, para não reimplementar algo já existente, mas infelizmente não encontrei o seu. Se o tivesse encontrado antes, teria contribuído com o seu projeto ao invés de criar outro.

Apesar deste contexto, fiquei muito feliz em ter encontrado o seu projeto. Dei uma olhada na sua implementação e achei muito bem feita e estruturada, parabéns. Estou neste momento com cerca de 60% da ideia inicial do meu projeto concluída, ainda restanto adicionar testes e implementar a funcionalidade de "crawler" do sistema do CEI-B3. Se você permitir, pretendo estudar a sua implementação de comunicação com o sistema CEI para tentar utilizá-la no meu sistema também. 

Espero que possamos entrar em contato para discutirmos novidades e novas ideias para esses projetos.

Atenciosamente,
Renan

**Comment by guilhermecgs** [comment]
oi renan,

bacana seu projeto. Eu também havia pesquisado antes e nao encontrei nada. Realmente sao bastante parecidos

Copia o crawler da B3 que irá funcionar beleza. Ele ira te retornar os trades em um dataframe.
Tem um codigo de teste também. O site do CEI é muito ruim, fica fora do ar sempre, mas funciona.

O que vc vai precisar será armazenar os trades em algum local, visto que no CEI so armazena por alguns meses. No meu caso, coloquei tudo no dropbox para conseguir editar manualmente de forma simples.

O que eu vou tentar da uma olhada no seu projeto é o modulo de calculo de IR. No meu, está tudo ok, mas nao tem algumas regras como 20K isencao, emolumentos e day trade. Se puder copiar eu vou copiar.

Vamos conversando sim: meu email é guilhermecgs@gmail.com

**Comment by renanleonellocastro** [comment]
Legal! Obrigado pelas dicas!

Podia conferir lá também os cálculos. Como ainda não fiz muitos testes, talvez ainda tenha erros. Uma outra questão também que já vou adiantar e lhe pedir desculpas é quanto a estrutura do código na parte de cálculo. Eu fui percebendo erros e consertando-os e, devido a isso, a parte de cálculo está bem confusa, mas pretendo enxugá-la em breve para deixar mais estruturado.

Vou mandar um e-mail para você para manter-mos contato.

Um abraço,
Renan
