### ISSUE TITLE
Participar no Hacktoberfest 2020 Ajudando a desenvolver

### ISSUE THREAD

**Issue by adalbertobrant** [guilhermecgs/ir#8]
Olá Guilherme.

  Como posso contribuir com o seu projeto, esta muito bacana, parabéns.
  
  Poderia me explicar qual a necessidade de upgrade  testes ou novas funcionalidades necessárias para o projeto avançar?

  Obrigado 

  Adalberto

**Comment by adalbertobrant** [comment]
Acabei de ler o README.md , já sei o que fazer.

Obrigado.

Adalberto

**Comment by guilhermecgs** [comment]
@adalbertobrant, aumentando a cobertura dos testes unitários já ajudaria bastante.

**Comment by adalbertobrant** [comment]
Blz posso fazer isso, como eu faço esses testes tem algum manual?

**Comment by guilhermecgs** [comment]
Seria fazer os testes unitários parecidos com esse codigo ( https://github.com/guilhermecgs/ir/blob/master/tests/test_crawler_b3_etfs.py) para a classe calculo_ir.py
